---
- name: Install postgresql
  become: true
  ansible.builtin.package:
    cache_valid_time: 3600
    pkg:
      - postgresql
      - postgresql-client
      - python3-psycopg
  tags:
    - package

- name: Place backup script
  become: true
  ansible.builtin.copy:
    src: restic-postgresql.sh
    dest: /etc/restic-backup/setup/restic-postgresql.sh
    owner: root
    group: root
    mode: '0755'
